import argparse
import asyncio
import logging

from tts_client.tts_protocol import tts_inject_snippet


def _get_argparser():
    parser = argparse.ArgumentParser(description="Tabletop Simulator Dev server")
    parser.add_argument(
        "--output-dir",
        type=str,
        help="The output path for autogenerated files what will be consumed when sending files",
    )
    parser.add_argument(
        "--file",
        type=str,
        help="File to execute",
    )
    parser.add_argument(
        "--libdir", help="Path to search for ttslua libs", action="append"
    )

    parser.add_argument(
        "-v", "--verbose", help="increase output verbosity", action="store_true"
    )
    return parser


if __name__ == "__main__":
    parser = _get_argparser()
    args = parser.parse_args()
    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)

    # snippet = args.selected_text
    asyncio.run(
        tts_inject_snippet(file_path=args.file, export_dir=args.output_dir, lib_dirs=args.libdir)
    )
