# coding: utf-8

import asyncio
import logging
import os
import argparse
import sys

from tts_lua.yarn_installer import yarn_check_install
from tts_server import tts_serve

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")


def _get_argparser():
    parser = argparse.ArgumentParser(description="Tabletop Simulator Dev server")
    parser.add_argument(
        "--output-dir",
        type=str,
        help="The output path for autogenerated files (WARNING : the files inside will be ALL removed and replaced)",
        required=False,
    )
    parser.add_argument(
        "--dont-check-yarn",
        type=bool,
        help="Don't check yarn package version at startup",
        default=True,
        required=False,
    )
    parser.add_argument(
        "--track-files",
        type=bool,
        help="Let the server track file tree and modification times. Necessary to use light push",
        default=True,
        required=False,
    )
    parser.add_argument(
        "--ws-port",
        type=int,
        help="Additional websocket proxy to TTS",
        default=None,
        required=False,
    )
    parser.add_argument(
        "--libdir", help="Path to search for ttslua libs", action="append"
    )

    parser.add_argument(
        "-v", "--verbose", help="increase output verbosity", action="store_true"
    )
    return parser


if __name__ == "__main__":
    parser = _get_argparser()
    args = parser.parse_args()
    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)

    if args.output_dir:
        if not os.path.isdir(args.output_dir):
            raise ValueError(f"Directory {args.output_dir} doesn't exists")
    if not args.dont_check_yarn:
        yarn_check_install()

    logging.debug("Starting")
    asyncio.run(tts_serve(export_dir=args.output_dir, lib_dirs=args.libdir, track_files=args.track_files, websocket_port=args.ws_port))
